# Generated by Django 4.2.4 on 2023-08-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='upload',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
