# Generated by Django 4.2.4 on 2023-08-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_name_document_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user_name',
            new_name='user',
        ),
    ]
