# Generated by Django 4.2.4 on 2023-08-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_rename_category_name_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
