version: "3"

services:
  web:
    restart: always
    build: .
    command: gunicorn futsal.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static:/code/futsal-backend/static
    mem_limit: 1g
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  nginx:
    restart: on-failure
    image: nginx:latest
    ports:
      - "8080:80" # Change the host port to 8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
volumes:
  static:
