# Generated by Django 4.2.4 on 2023-08-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_data',
        ),
    ]
